feat(adapter-configuration-validation):  do not mix legacy and new parameters (#450)
For legacy + custom interceptos chain:

```
Traceback (most recent call last):
  File "/opt/venv/bin/nemo-evaluator", line 7, in <module>
    sys.exit(run_eval())
             ^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/nemo_evaluator/core/entrypoint.py", line 188, in run_eval
    run(args)
  File "/opt/venv/lib/python3.12/site-packages/nemo_evaluator/core/entrypoint.py", line 145, in run
    adapter_config = AdapterConfig.get_validated_config(run_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/nemo_evaluator/adapters/adapter_config.py", line 194, in get_validated_config
    raise ValueError(
ValueError: Cannot use legacy configuration parameters when interceptors are explicitly defined in target.api_endpoint.adapter_config. Found: caching_dir, generate_html_report, html_report_size, tracking_requests_stats. Please remove these and configure using interceptors instead.

```

tests also with only custom interceptors chain, only legacy params,
nothing passed (default values used) and running with --run_config

---------

Signed-off-by: Anna Warno <awarno@nvidia.com>