fix(tests): unfix ports and unflake (#453)
I think due to environment manipulation, some flakes like this
https://github.com/NVIDIA-NeMo/Evaluator/actions/runs/19317563423/job/55252056077#step:3:5132
have happened

> ```  
> =========================== short test summary info
============================
> FAILED tests/unit_tests/core/test_metadata.py::test_metadata_full -
OSError: Adapter server was requested to start explicitly on 3825
through '...
> FAILED tests/unit_tests/core/test_metadata.py::test_no_metadata -
OSError: Adapter server was requested to start explicitly on 3825
through '...
> FAILED
tests/unit_tests/core/test_metadata.py::test_env_versioning_and_resolved_only
- OSError: Adapter server was requested to start explicitly on 3825
through '...
> FAILED
tests/unit_tests/core/test_metadata.py::test_only_versioning_no_env -
OSError: Adapter server was requested to start explicitly on 3825
through '...
> ERROR
tests/unit_tests/utils/test_cache_utils.py::test_get_token_usage_from_cache_db_single_request
- OSError: Adapter server was requested to start explicitly on 3825
through '...
> ERROR
tests/unit_tests/utils/test_cache_utils.py::test_get_token_usage_from_cache_db_multiple_requests
- OSError: Adapter server was requested to start explicitly on 3825
through '...
> ```

This fixes it and couple of other smaller bugs on the way

---------

Signed-off-by: Alex Gronskiy <agronskiy@nvidia.com>